---
output:
  html_document:
    pandoc_args: [
      "+RTS", "-K64m",
      "-RTS" 
    ]
---


## Steps

There is an inverse relationship between alcohol content and white wine's density. The less alcohol content a wine had, the more dense it was. This could be due to other substances within the wine that's replacing the density of alcohol with a higher density.

The better the quality of the wines, the more alcohol content that the wine contains. Also, the highest average alcohol content is concentrated around wine that have PH levels of 3.2 - 3.4. 


The key performance indicator (KPI) that we analyzed was Citric Acid / Sugar levels. This can show how sour or sweet a particular white wine tastes. The numbers shown are the citric acid level, residual sugar level, and the KPI of a particular wine with specific PH and quality levels. The colors help show if a partciular wine with those characteristics have a high, low, or medium KPI. A high KPI shows that a wine is more sour, a low kPI shows that a wine is more sweet, and a medium KPI shows a good balance between sweet and sour.


To reproduce the crosstab table in R, select variable names to the variables used in Tableau, such as pH, Quality, sum of Citric acid, sum of residual sugar, and KPI. The graph produced by R has to be zoomed to see the pH, Quality, sum of Citric Acid, and sum of residual sugar in text format.  

To reproduce the Bar chart in R, select variable names to the variables used in Tableau, such as quality, pH, and average alcohol content. 

To reproduce the scatterplot in R, select variable names to the variables used in Tableau, such as alcohol for the X axis and Density for the Y axis.


For shiny, the ui file contains the three slides for each visualization.
Ther server file refers to the ui file, and produces the three visualizations. The first one being the crosstab, the second being the barchart, and the third being the scatter plot. 

https://shs855.shinyapps.io/Shiny_DVS_Project1
